export interface Usuario{
    responsable:string,
    equipo:string,
    marca:string,
    modelo:string,
    serie:string,
    mac_alambrica:string,
    mac_inalambrica:string,
    ip_alambrica:string,
    ip_inalambrica:string,
    ordinal:string,
    compra:string,
    estado:string,
    observaciones:string,
}
